### ISSUE TITLE
JavaScript/Conclusion: Gramma mistake/typo in the feedback form. 

### ISSUE THREAD

**Issue by HiDeny** [TheOdinProject/curriculum#26775]
### Describe your suggestion

There is a typo on the Google Forms questionnaire in the end of the course:
"If **your doing** the JavaScript path, **n** a scale of 1 being poor to 5 being great and would not change anything. How would you rate your experience so far?"

"Your doing" should be "you're doing" (this is in the previous question on Ruby as well)
"n" should be "on"

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/javascript-conclusion

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [ ] Would you like to work on this issue?

### (Optional) Discord Name

HiDeny

**Comment by dmaret** [comment]
Hi, I would like to work on this issue.

**Comment by HiDeny** [comment]
> Hi I would like to work on this issue, if possible. Also the lesson URL mentioned in the issue is incorrect. It leads me to creating a new issue. The correct link to the lesson is: https://www.theodinproject.com/lessons/javascript-conclusion

Link is fixed! Thanks.

**Comment by KevinMulhern** [comment]
Would you mind taking a look at this one please @linkonsat?

**Comment by 01zulfi** [comment]
@linkonsat, did you look at it?

**Comment by KevinMulhern** [comment]
Thanks for the report @HiDeny, this has been fixed

<img width="396" alt="Screenshot 2024-01-29 at 08 31 20" src="https://github.com/TheOdinProject/curriculum/assets/7963776/b8299f1c-4cbe-4191-8015-1443d2320dfe">

**Comment by George-Gabechava** [comment]
Hello, has this change been implemented? I still see the issue in the lesson: https://www.theodinproject.com/lessons/node-path-javascript-conclusion

**Comment by KevinMulhern** [comment]
Whoops, looks like I updated the wrong thing before. Thanks for pointing it out @George-Gabechava, it should be fixed now.
